Repository NethermindEth/sedge, pull requests merged in 2022-07, with the labels that each got.

#51 Typo fixes + language changes
  README.md
Labels: documentation

#49 Fix prysm posmonit monitoring
  cli/cli.go
  cli/cli_test.go
  cli/cli_utils.go
  cli/keys.go
  configs/messages.go
  internal/pkg/generate/generate_scripts.go
  internal/pkg/generate/generate_scripts_test.go
  internal/pkg/generate/types.go
  templates/deposit-cli/existing.tmpl
  templates/deposit-cli/new.tmpl
  templates/envs/kiln/consensus/lodestar.tmpl
  templates/envs/kiln/validator/prysm.tmpl
  templates/envs/mainnet/validator/prysm.tmpl
  templates/scripts/jwt_secret.sh
  templates/services/mainnet/consensus/prysm.tmpl
  templates/services/mainnet/validator/prysm.tmpl
  templates/services/merge/consensus/prysm.tmpl
  templates/services/merge/validator/prysm.tmpl
Labels: bug, on-premise

#58 Add Changelog
  CHANGELOG.md
  CONTRIBUTING.md
  Makefile
  README.md
  cmd/sedge/main.go
Labels: documentation

#57 Release pipeline v1
  .github/workflows/build.yml
  scripts/build-go-binaries.sh
Labels: devops

#59 jwtsecret generation bug
  CHANGELOG.md
  cli/cli.go
  cli/cli_utils.go
Labels: bug

#60 Bugfix and Readme update
  CHANGELOG.md
  README.md
  cli/cli_test.go
  cli/cli_utils.go
  cli/down.go
  configs/errors.go
  internal/pkg/commands/cmd_runner_unix.go
  internal/utils/checks.go
  internal/utils/checks_test.go
  templates/envs/ropsten/validator/lighthouse.tmpl
  templates/setup/linux/docker/ubuntu_20.04.sh
  templates/setup/linux/docker/ubuntu_22.04.sh
Labels: bug, documentation

#61 Fix Lighthouse template
  templates/services/merge/consensus/lighthouse.tmpl
Labels: bug

#63 Fix prysm env template network configs
  templates/envs/ropsten/consensus/prysm.tmpl
Labels: bug
