Repository NethermindEth/sedge, pull requests merged in 2022-08, with the labels that each got.

#62 Add Prater Network
  .github/workflows/release.yml
  CHANGELOG.md
  CONTRIBUTING.md
  Makefile
  README.md
  cli/cli.go
  cli/cli_test.go
  cli/cli_utils.go
  cli/down.go
  cmd/main.go
  cmd/sedge/main.go
  configs/errors.go
  configs/init.go
  configs/messages.go
  go.mod
  internal/pkg/commands/cmd_runner_unix.go
  internal/pkg/generate/generate_scripts.go
  internal/pkg/generate/types.go
  internal/utils/checks.go
  internal/utils/checks_test.go
  internal/utils/networks_test.go
  internal/utils/utils_test.go
  scripts/build-go-binaries.sh
  templates/envs/prater/consensus/lighthouse.tmpl
  templates/envs/prater/consensus/lodestar.tmpl
  templates/envs/prater/consensus/prysm.tmpl
  templates/envs/prater/consensus/teku.tmpl
  templates/envs/prater/env_base.tmpl
  templates/envs/prater/execution/geth.tmpl
  templates/envs/prater/execution/nethermind.tmpl
  templates/envs/prater/validator/lighthouse.tmpl
  templates/envs/prater/validator/lodestar.tmpl
  templates/envs/prater/validator/prysm.tmpl
  templates/envs/prater/validator/teku.tmpl
  templates/envs/ropsten/consensus/prysm.tmpl
  templates/envs/ropsten/validator/lighthouse.tmpl
  templates/envs/ropsten/validator/prysm.tmpl
  templates/services/merge/consensus/lighthouse.tmpl
  templates/services/merge/consensus/lodestar.tmpl
  templates/services/merge/consensus/prysm.tmpl
  templates/services/merge/consensus/teku.tmpl
  templates/services/merge/execution/geth.tmpl
  templates/services/merge/execution/nethermind.tmpl
  templates/services/merge/validator/lighthouse.tmpl
  templates/services/merge/validator/lodestar.tmpl
  templates/services/merge/validator/prysm.tmpl
  templates/setup/linux/docker/ubuntu_20.04.sh
  templates/setup/linux/docker/ubuntu_22.04.sh
Labels: on-premise, new network

#65 Initial documentation
  .github/workflows/build.yml
  .github/workflows/docs-deploy.yml
  .github/workflows/docs-test.yml
  CHANGELOG.md
  README.md
  docs/.gitignore
  docs/Makefile
  docs/README.md
  docs/babel.config.js
  docs/docs/concepts/_category_.json
  docs/docs/concepts/fee-recipient.md
  docs/docs/concepts/keystore.md
  docs/docs/intro.md
  docs/docs/overview/_category_.json
  docs/docs/overview/architecture.md
  docs/docs/overview/design.md
  docs/docs/overview/features.md
  docs/docs/quickstart/_category_.json
  docs/docs/quickstart/complete-guide.md
  docs/docs/quickstart/dependencies.mdx
  docs/docs/quickstart/hardware-requirements/_category_.json
  docs/docs/quickstart/hardware-requirements/index.md
  docs/docs/quickstart/hardware-requirements/mainnet.md
  docs/docs/quickstart/hardware-requirements/testnets.md
  docs/docs/quickstart/index.md
  docs/docs/quickstart/install-guide.mdx
  docs/docs/quickstart/run-validator-mev-ropsten.md
  docs/docs/quickstart/run-validator.md
  docs/docs/troubleshoot.md
  docs/docusaurus.config.js
  docs/package-lock.json
  docs/package.json
  docs/sidebars.js
  docs/src/components/HomepageFeatures/index.js
  docs/src/components/HomepageFeatures/styles.module.css
  docs/src/css/custom.css
  docs/src/pages/index.js
  docs/src/pages/index.module.css
  docs/src/pages/markdown-page.md
  docs/static/.nojekyll
  docs/static/CNAME
  docs/static/img/docusaurus.png
  docs/static/img/favicon.ico
  docs/static/img/logo.svg
  docs/static/img/undraw_docusaurus_mountain.svg
  docs/static/img/undraw_docusaurus_react.svg
  docs/static/img/undraw_docusaurus_tree.svg
  internal/pkg/commands/cmd_runner_helper_unix.go
Labels: documentation, main, devops

#66 Add Sepolia network
  configs/init.go
  internal/utils/networks_test.go
  templates/envs/prater/execution/geth.tmpl
  templates/envs/sepolia/consensus/lighthouse.tmpl
  templates/envs/sepolia/consensus/lodestar.tmpl
  templates/envs/sepolia/consensus/prysm.tmpl
  templates/envs/sepolia/consensus/teku.tmpl
  templates/envs/sepolia/env_base.tmpl
  templates/envs/sepolia/execution/geth.tmpl
  templates/envs/sepolia/execution/nethermind.tmpl
  templates/envs/sepolia/validator/lighthouse.tmpl
  templates/envs/sepolia/validator/lodestar.tmpl
  templates/envs/sepolia/validator/prysm.tmpl
  templates/envs/sepolia/validator/teku.tmpl
  templates/services/merge/consensus/prysm.tmpl
  templates/services/merge/execution/nethermind.tmpl
Labels: on-premise, new network

#67 Update mev-boost settings
  CHANGELOG.md
  README.md
  templates/envs/kiln/env_base.tmpl
  templates/envs/prater/env_base.tmpl
  templates/envs/prater/validator/lighthouse.tmpl
  templates/envs/prater/validator/lodestar.tmpl
  templates/envs/prater/validator/prysm.tmpl
  templates/envs/prater/validator/teku.tmpl
  templates/envs/sepolia/env_base.tmpl
  templates/services/docker-compose_base.tmpl
  templates/services/merge/consensus/lodestar.tmpl
  templates/services/merge/consensus/prysm.tmpl
  templates/services/merge/consensus/teku.tmpl
  templates/services/merge/validator/lighthouse.tmpl
  templates/services/merge/validator/lodestar.tmpl
  templates/services/merge/validator/prysm.tmpl
  templates/services/merge/validator/teku.tmpl
Labels: main

#68 Update documentation
  CHANGELOG.md
  README.md
  cli/cli.go
  docs/docs/intro.md
  docs/docs/overview/config-file.md
  docs/docs/quickstart/complete-guide.mdx
  docs/docusaurus.config.js
  docs/src/css/custom.css
Labels: documentation

#81 Add Disclaimers
  README.md
  cli/version.go
  cli/version_test.go
  docs/docs/intro.md
  docs/docs/quickstart/complete-guide.mdx
  docs/docs/quickstart/hardware-requirements/index.md
  docs/docs/quickstart/install-guide.mdx
Labels: documentation, main

#82 Add Testnets support
  CHANGELOG.md
  Makefile
  README.md
  cli/logs.go
  cli/logs_test.go
  configs/init.go
  configs/messages.go
  internal/pkg/commands/cmd_runner_unix.go
  internal/pkg/env/get_variable.go
  internal/pkg/env/get_variable_test.go
  internal/pkg/env/regex.go
  internal/pkg/generate/generate_config_test.go
  internal/pkg/generate/generate_scripts.go
  internal/pkg/generate/types.go
  internal/utils/checks.go
  internal/utils/networks_test.go
  templates/envs/chiado/consensus/lighthouse.tmpl
  templates/envs/chiado/consensus/lodestar.tmpl
  templates/envs/chiado/consensus/prysm.tmpl
  templates/envs/chiado/consensus/teku.tmpl
  templates/envs/chiado/env_base.tmpl
  templates/envs/chiado/execution/nethermind.tmpl
  templates/envs/chiado/validator/lighthouse.tmpl
  templates/envs/chiado/validator/lodestar.tmpl
  templates/envs/chiado/validator/prysm.tmpl
  templates/envs/chiado/validator/teku.tmpl
  templates/envs/denver/consensus/lighthouse.tmpl
  templates/envs/denver/consensus/lodestar.tmpl
  templates/envs/denver/consensus/prysm.tmpl
  templates/envs/denver/consensus/teku.tmpl
  templates/envs/denver/env_base.tmpl
  templates/envs/denver/execution/nethermind.tmpl
  templates/envs/denver/validator/lighthouse.tmpl
  templates/envs/denver/validator/lodestar.tmpl
  templates/envs/denver/validator/prysm.tmpl
  templates/envs/denver/validator/teku.tmpl
  templates/envs/kiln/consensus/lodestar.tmpl
  templates/envs/kiln/consensus/prysm.tmpl
  templates/envs/kiln/validator/lodestar.tmpl
  templates/envs/mainnet/consensus/lodestar.tmpl
  templates/envs/mainnet/validator/lodestar.tmpl
  templates/envs/prater/consensus/lodestar.tmpl
  templates/envs/prater/consensus/prysm.tmpl
  templates/envs/prater/validator/lodestar.tmpl
  templates/envs/ropsten/consensus/lodestar.tmpl
  templates/envs/ropsten/consensus/prysm.tmpl
  templates/envs/ropsten/validator/lodestar.tmpl
  templates/envs/sepolia/consensus/lodestar.tmpl
  templates/envs/sepolia/consensus/prysm.tmpl
  templates/envs/sepolia/validator/lodestar.tmpl
  templates/services/docker-compose_base.tmpl
  templates/services/merge/consensus/lighthouse.tmpl
  templates/services/merge/consensus/lodestar.tmpl
  templates/services/merge/consensus/prysm.tmpl
  templates/services/merge/consensus/teku.tmpl
  templates/services/merge/validator/lighthouse.tmpl
  templates/services/merge/validator/lodestar.tmpl
  templates/services/merge/validator/prysm.tmpl
  templates/services/merge/validator/teku.tmpl
Labels: on-premise, new network

#83 Exclude validator from full node setup
  CHANGELOG.md
  cli/cli.go
  internal/pkg/clients/clients_test.go
  internal/pkg/clients/types.go
  internal/pkg/clients/utils_test.go
  internal/pkg/generate/generate_scripts.go
  internal/pkg/generate/generate_scripts_test.go
  internal/pkg/generate/types.go
  internal/utils/utils.go
  internal/utils/utils_test.go
  templates/services/mainnet/validator/empty.tmpl
  templates/services/merge/validator/empty.tmpl
Labels: enhancement, on-premise

#85 Update docs deploy
  .github/workflows/docs-deploy.yml
Labels: devops

#73 Add Gnosis Network
  CHANGELOG.md
  configs/init.go
  internal/pkg/generate/generate_scripts.go
  internal/utils/networks_test.go
  templates/envs/gnosis/consensus/lighthouse.tmpl
  templates/envs/gnosis/consensus/lodestar.tmpl
  templates/envs/gnosis/consensus/prysm.tmpl
  templates/envs/gnosis/consensus/teku.tmpl
  templates/envs/gnosis/env_base.tmpl
  templates/envs/gnosis/execution/nethermind.tmpl
  templates/envs/gnosis/validator/lighthouse.tmpl
  templates/envs/gnosis/validator/lodestar.tmpl
  templates/envs/gnosis/validator/prysm.tmpl
  templates/envs/gnosis/validator/teku.tmpl
Labels: enhancement, on-premise, new network, main

#93 Fix wrong download link in installation guide
  docs/docs/quickstart/install-guide.mdx
Labels: bug, documentation
