Repository NethermindEth/sedge, pull requests merged in 2022-10, with the labels that each got.

#121 Print generated files as string instead []byte
  CHANGELOG.md
  internal/ui/files.go
Labels: bug

#131 Add support for mev-boost on mainnet
  CHANGELOG.md
  templates/envs/mainnet/env_base.tmpl
  templates/envs/mainnet/validator/lighthouse.tmpl
  templates/envs/mainnet/validator/lodestar.tmpl
  templates/envs/mainnet/validator/prysm.tmpl
  templates/envs/mainnet/validator/teku.tmpl
Labels: enhancement

#125 Check for newer releases
  CHANGELOG.md
  Makefile
  cli/root.go
  cli/version.go
  configs/messages.go
  go.mod
  go.sum
  internal/utils/utils_test.go
  internal/utils/version.go
  internal/utils/version_test.go
  scripts/build-go-binaries.sh
Labels: enhancement

#135 Fix keystore permissions when saving
  CHANGELOG.md
  cli/keys.go
  internal/pkg/commands/cmd_runner_unix.go
  internal/pkg/commands/commands.go
  internal/pkg/commands/commands_test.go
  internal/pkg/commands/types.go
  test/test.go
Labels: bug

#136 Add documentation to run the node by yourself
  CHANGELOG.md
  docs/docs/quickstart/by-yourself.mdx
  docs/docs/quickstart/complete-guide.mdx
Labels: documentation

#112 Fix Installation Guide download commands
  README.md
  docs/docs/quickstart/complete-guide.mdx
  docs/docs/quickstart/install-guide.mdx
Labels: documentation

#138 Update prysm version for gnosis
  scripts/check-image-updates.sh
Labels: devops

#144 Fix version not embedded on binary
  Makefile
  scripts/build-go-binaries.sh
Labels: bug

#146 Change AdditionalPortUrl for EngineHost and EnginePort
  templates/services/merge/execution/nethermind.tmpl
Labels: bug

#140 Keystores Generation
  CHANGELOG.md
  cli/cli.go
  cli/keys.go
  cli/keys_test.go
  cli/keys_utils.go
  cli/testdata/keys_tests/case_1/config/pass.txt
  configs/errors.go
  configs/init.go
  configs/messages.go
  configs/types.go
  go.mod
  go.sum
  internal/pkg/generate/clean_scripts.go
  internal/pkg/generate/generate_scripts.go
  internal/pkg/keystores/keystore_external_utils.go
  internal/pkg/keystores/types.go
  internal/ui/files.go
Labels: enhancement, on-premise, main

#147 Update validator import services
  templates/services/merge/validator/lighthouse.tmpl
  templates/services/merge/validator/lodestar.tmpl
Labels: enhancement, main

#143 Add documentation for chiado
  CHANGELOG.md
  docs/docs/quickstart/chiado.mdx
Labels: documentation

#153 Update Documentation
  README.md
  docs/docs/intro.md
  docs/docs/quickstart/by-yourself.mdx
  docs/docs/quickstart/chiado.mdx
  docs/docs/quickstart/complete-guide.mdx
  docs/docusaurus.config.js
Labels: documentation
