Repository NethermindEth/sedge, pull requests merged in 2022-12, with the labels that each got.

#123 Add Besu Execution Client
  CHANGELOG.md
  README.md
  config.yaml
  scripts/check-image-updates.sh
  templates/envs/goerli/execution/besu.tmpl
  templates/envs/mainnet/execution/besu.tmpl
  templates/envs/sepolia/execution/besu.tmpl
  templates/services/merge/execution/besu.tmpl
Labels: enhancement, main

#156 Add Erigon Execution Client
  CHANGELOG.md
  README.md
  config.yaml
  scripts/check-image-updates.sh
  templates/envs/goerli/execution/erigon.tmpl
  templates/envs/mainnet/execution/erigon.tmpl
  templates/envs/sepolia/execution/erigon.tmpl
  templates/services/merge/execution/erigon.tmpl
Labels: enhancement

#184 [Fix] AssignPorts test
  CHANGELOG.md
  cli/cli_test.go
  internal/pkg/generate/generate_scripts.go
  internal/utils/utils.go
  internal/utils/utils_test.go
Labels: bug

#171 Add Windows platform
  CHANGELOG.md
  cli/cli.go
  cli/cli_test.go
  cli/cli_utils.go
  cli/down.go
  cli/down_test.go
  cli/keys.go
  cli/keys_utils.go
  cli/logs.go
  cli/logs_test.go
  cmd/sedge/main.go
  configs/errors.go
  go.mod
  go.sum
  internal/crypto/crypto.go
  internal/pkg/clients/clients.go
  internal/pkg/clients/clients_test.go
  internal/pkg/commands/cmd_runner_helper_unix.go
  internal/pkg/commands/cmd_runner_unix.go
  internal/pkg/commands/cmd_runner_utils.go
  internal/pkg/commands/cmd_runner_windows.go
  internal/pkg/commands/commands.go
  internal/pkg/commands/commands_test.go
  internal/pkg/commands/commands_test_unix.go
  internal/pkg/commands/commands_test_windows.go
  internal/pkg/commands/types.go
  internal/pkg/env/check_variable.go
  internal/pkg/env/get_variable.go
  internal/pkg/generate/generate_config.go
  internal/pkg/generate/generate_scripts.go
  internal/ui/tables_test.go
  internal/utils/checks.go
  internal/utils/checks_test.go
  internal/utils/deposit_cli.go
  internal/utils/deposit_cli_test.go
  internal/utils/handle_dependencies.go
  internal/utils/handle_dependencies_test.go
  internal/utils/utils_unix.go
  internal/utils/utils_windows.go
  internal/utils/version.go
  templates/scripts/jwt_secret.sh
  templates/templates.go
  test/test.go
Labels: main

#166 [Fix] Validator restart failure
  CHANGELOG.md
  cli/cli.go
  cli/cli_test.go
  cli/cli_utils.go
  configs/networks.go
  go.mod
  go.sum
  internal/pkg/generate/generate_scripts.go
  internal/pkg/generate/types.go
  internal/pkg/generate/types_test.go
  templates/services/docker-compose_base.tmpl
  templates/services/merge/consensus/lighthouse.tmpl
  templates/services/merge/consensus/lodestar.tmpl
  templates/services/merge/consensus/prysm.tmpl
  templates/services/merge/consensus/teku.tmpl
  templates/services/merge/validator/lighthouse.tmpl
  templates/services/merge/validator/lodestar.tmpl
  templates/services/merge/validator/prysm.tmpl
  templates/services/merge/validator/teku.tmpl
  templates/services/validator-blocker.tmpl
Labels: bug

#169 [Feat] Show mnemonic without a trace
  CHANGELOG.md
  cli/keys.go
  cli/keys_test.go
  cmd/sedge/main.go
  configs/errors.go
  configs/messages_unix.go
  configs/messages_windows.go
  internal/pkg/commands/cmd_runner_unix.go
  internal/pkg/commands/cmd_runner_windows.go
  internal/pkg/commands/commands.go
  internal/pkg/commands/types.go
  test/test.go
Labels: bug, enhancement

#191 Slashing protection
  CHANGELOG.md
  cli/actions/actions.go
  cli/actions/errors.go
  cli/actions/slashing.go
  cli/actions/slashing_test.go
  cli/cli.go
  cli/cli_test.go
  cli/cli_utils.go
  cli/slashingExport.go
  cmd/sedge/main.go
  configs/messages.go
  configs/paths.go
  go.mod
  go.sum
  internal/pkg/commands/cmd_runner_unix.go
  internal/pkg/commands/commands.go
  internal/pkg/commands/types.go
  internal/pkg/generate/generate_scripts.go
  internal/pkg/services/containerId.go
  internal/pkg/services/containerId_test.go
  internal/pkg/services/errors.go
  internal/pkg/services/image.go
  internal/pkg/services/image_test.go
  internal/pkg/services/isRunning.go
  internal/pkg/services/isRunning_test.go
  internal/pkg/services/services.go
  internal/pkg/services/start.go
  internal/pkg/services/start_test.go
  internal/pkg/services/stop.go
  internal/pkg/services/stop_test.go
  internal/pkg/services/wait.go
  internal/pkg/services/wait_test.go
  internal/utils/copy.go
  templates/services/merge/validator/prysm.tmpl
  test/mock_docker/apiClient.go
  test/test.go
Labels: enhancement

#192 Warn about use --network framework on sedge keys
  docs/docs/quickstart/complete-guide.mdx
Labels: documentation

#204 Add commands to documentation
  docs/docs/commands/_category_.json
  docs/docs/commands/cli.mdx
  docs/docs/commands/clients.mdx
  docs/docs/commands/down.mdx
  docs/docs/commands/keys.mdx
  docs/docs/commands/logs.mdx
  docs/docs/commands/networks.mdx
  docs/docs/commands/version.mdx
  docs/docs/overview/config-file.md
  docs/docs/quickstart/complete-guide.mdx
Labels: documentation

#164 Fix tag on pre release
  .github/workflows/release.yml
  CHANGELOG.md
  scripts/build-go-darwin-binaries.sh
  scripts/build-go-linux-binaries.sh
Labels: bug

#203 Add `run` command
  CHANGELOG.md
  cli/actions/actions.go
  cli/actions/errors.go
  cli/actions/installDeps.go
  cli/actions/run.go
  cli/actions/run_test.go
  cli/actions/setup.go
  cli/actions/setup_test.go
  cli/actions/slashing.go
  cli/actions/slashing_test.go
  cli/cli.go
  cli/cli_test.go
  cli/cli_utils.go
  cli/run.go
  cmd/sedge/main.go
  docs/docs/commands/run.mdx
  internal/pkg/commands/cmd_runner_unix.go
  internal/pkg/commands/cmd_runner_windows.go
Labels: enhancement

#207 Remove config file
  CHANGELOG.md
  README.md
  cli/cli.go
  cli/cli_test.go
  cli/down_test.go
  cli/keys.go
  cli/keys_test.go
  cli/listClients.go
  cli/listClients_test.go
  cli/logs_test.go
  cli/root.go
  cli/root_test.go
  config.yaml
  configs/get_clients.go
  configs/get_clients_test.go
  configs/init.go
  docs/docs/commands/cli.mdx
  docs/docs/commands/clients.mdx
  docs/docs/commands/down.mdx
  docs/docs/commands/keys.mdx
  docs/docs/commands/logs.mdx
  docs/docs/commands/networks.mdx
  docs/docs/commands/version.mdx
  docs/docs/overview/config-file.md
  internal/pkg/clients/clients.go
  internal/pkg/clients/clients_test.go
  internal/pkg/clients/types.go
  internal/pkg/generate/generate_scripts.go
  internal/pkg/generate/generate_scripts_test.go
  templates/envs/gnosis/consensus/prysm.tmpl
Labels: enhancement
