Repository NethermindEth/sedge, pull requests merged in 2022-11, with the labels that each got.

#155 Update documentation
  README.md
  docs/docs/intro.md
  docs/docs/quickstart/chiado.mdx
  docs/docs/quickstart/complete-guide.mdx
  docs/docs/quickstart/install-guide.mdx
Labels: documentation

#154 Add logging flag
  cli/cli.go
  cli/keys_test.go
  configs/errors.go
  configs/init.go
  configs/logging.go
  internal/pkg/generate/generate_scripts.go
  internal/pkg/generate/types.go
  internal/pkg/keystores/keystore_external_utils.go
  internal/utils/version.go
  templates/services/docker-compose_base.tmpl
  templates/services/merge/consensus/lighthouse.tmpl
  templates/services/merge/consensus/lodestar.tmpl
  templates/services/merge/consensus/prysm.tmpl
  templates/services/merge/consensus/teku.tmpl
  templates/services/merge/execution/geth.tmpl
  templates/services/merge/execution/nethermind.tmpl
  templates/services/merge/validator/lighthouse.tmpl
  templates/services/merge/validator/lodestar.tmpl
  templates/services/merge/validator/prysm.tmpl
  templates/services/merge/validator/teku.tmpl
Labels: enhancement

#158 [fix] Update passphrase prompt condition
  cli/keys.go
  cli/keys_test.go
  cli/keys_utils.go
  cli/prompts/cli.go
  cli/prompts/prompt.go
  cli/root.go
  cli/utils.go
  configs/init.go
  go.mod
  go.sum
  test/mock_prompts/prompt.go
Labels: bug

#161 [fix] Download service images before the run
  cli/cli_utils.go
  internal/pkg/commands/cmd_runner_unix.go
  internal/pkg/commands/commands.go
  internal/pkg/commands/types.go
  test/test.go
Labels: bug

#157 Enable metrics by default
  docs/docs/quickstart/complete-guide.mdx
  templates/envs/chiado/execution/nethermind.tmpl
  templates/envs/gnosis/execution/nethermind.tmpl
  templates/envs/goerli/execution/geth.tmpl
  templates/envs/goerli/execution/nethermind.tmpl
  templates/envs/mainnet/execution/geth.tmpl
  templates/envs/mainnet/execution/nethermind.tmpl
  templates/envs/sepolia/execution/geth.tmpl
  templates/envs/sepolia/execution/nethermind.tmpl
  templates/services/merge/execution/geth.tmpl
  templates/services/merge/execution/nethermind.tmpl
Labels: enhancement

#162 Refactor `cli` package
  cli/cli.go
  cli/cli_test.go
  cli/cli_utils.go
  cli/down.go
  cli/down_test.go
  cli/keys.go
  cli/keys_test.go
  cli/keys_utils.go
  cli/listClients.go
  cli/listClients_test.go
  cli/listNetworks.go
  cli/logs.go
  cli/logs_test.go
  cli/prompts/cli.go
  cli/prompts/prompt.go
  cli/root.go
  cli/root_test.go
  cli/version.go
  cli/version_test.go
  cmd/sedge/main.go
  test/mock_prompts/prompt.go
Labels: main

#172 Fix wrong gnosis fork version in networks configs
  CHANGELOG.md
  configs/init.go
Labels: bug

#177 Add missing depends_on tag to lodestar
  CHANGELOG.md
  templates/services/merge/validator/lodestar.tmpl
Labels: bug

#178 feat: update gnosis sync url on consensus client
  CHANGELOG.md
  templates/envs/gnosis/consensus/lighthouse.tmpl
  templates/envs/gnosis/consensus/lodestar.tmpl
  templates/envs/gnosis/consensus/prysm.tmpl
  templates/envs/gnosis/consensus/teku.tmpl
Labels: enhancement

#181 Add codecov token to upload action
  .github/workflows/unit_tests.yml
Labels: devops

#179 Add chiado checkpoint sync
  CHANGELOG.md
  templates/envs/chiado/consensus/lighthouse.tmpl
  templates/envs/chiado/consensus/lodestar.tmpl
  templates/envs/chiado/consensus/prysm.tmpl
  templates/envs/chiado/consensus/teku.tmpl
Labels: enhancement
