Repository NethermindEth/sedge, pull requests merged in 2022-01, with the labels that each got.

#1 Handle dependencies of setup tool
  .gitignore
  LICENSE
  Makefile
  api/README.md
  assets/README.md
  build/README.md
  cmd/1Click/main.go
  cmd/README.md
  cmd/cli.go
  cmd/listClients.go
  cmd/root.go
  cmd/version.go
  config.yaml
  configs/README.md
  configs/get_clients.go
  configs/get_dependencies.go
  configs/messages.go
  configs/types.go
  deployments/README.md
  docs/README.md
  examples/README.md
  go.mod
  go.sum
  init/README.md
  internal/README.md
  internal/utils/check_depedencies.go
  internal/utils/get_distro.go
  internal/utils/install_dependencies.go
  internal/utils/types.go
  internal/utils/zip.go
  pkg/README.md
  scripts/README.md
  scripts/setup/linux/docker-compose/amzn.sh
  scripts/setup/linux/docker-compose/centos.sh
  scripts/setup/linux/docker-compose/debian.sh
  scripts/setup/linux/docker-compose/fedora.sh
  scripts/setup/linux/docker-compose/ubuntu.sh
  scripts/setup/linux/docker/amzn.sh
  scripts/setup/linux/docker/centos.sh
  scripts/setup/linux/docker/debian.sh
  scripts/setup/linux/docker/fedora.sh
  scripts/setup/linux/docker/ubuntu.sh
  test/README.md
  third_party/README.md
  tools/README.md
  web/README.md
  website/README.md
Labels: on-premise, UI

#2 Install and show dependencies for on-premise setup [cli cmd]
  cmd/cli.go
  cmd/listClients.go
  cmd/root.go
  config.yaml
  configs/get_clients.go
  configs/messages.go
  configs/types.go
  go.mod
  go.sum
  internal/ui/tables.go
  internal/utils/get_distro.go
  internal/utils/handle_dependencies.go
  internal/utils/install_dependencies.go
  internal/utils/types.go
  internal/utils/utils.go
  internal/utils/zip.go
Labels: on-premise, UI

#4 CI integrations for 1Click
  .deepsource.toml
  .github/workflows/ci.yml
  Makefile
  go.mod
  go.sum
Labels: enhancement

#3 Generate docker compose scripts
  .github/workflows/ci.yml
  .gitignore
  Makefile
  cmd/cli.go
  cmd/listClients.go
  config.yaml
  configs/errors.go
  configs/get_clients.go
  configs/messages.go
  configs/types.go
  internal/pkg/clients/clients.go
  internal/pkg/clients/types.go
  internal/pkg/clients/utils.go
  internal/ui/tables.go
  internal/utils/generate_scripts.go
  internal/utils/get_distro.go
  internal/utils/types.go
  internal/utils/utils.go
  templates/envs/consensus/lighthouse.tmpl
  templates/envs/consensus/lodestar.tmpl
  templates/envs/consensus/prysm.tmpl
  templates/envs/consensus/teku.tmpl
  templates/envs/execution/nethermind.tmpl
  templates/envs/validator/lighthouse.tmpl
  templates/envs/validator/lodestar.tmpl
  templates/envs/validator/prysm.tmpl
  templates/envs/validator/teku.tmpl
  templates/services/consensus/lighthouse.tmpl
  templates/services/consensus/lodestar.tmpl
  templates/services/consensus/prysm.tmpl
  templates/services/consensus/teku.tmpl
  templates/services/docker-compose_base.tmpl
  templates/services/execution/nethermind.tmpl
  templates/services/validator/lighthouse.tmpl
  templates/services/validator/lodestar.tmpl
  templates/services/validator/prysm.tmpl
  templates/services/validator/teku.tmpl
  templates/templates.go
Labels: on-premise
