Repository NethermindEth/sedge, pull requests merged in 2023-04, with the labels that each got.

#273 InputURL issue with empty input
  CHANGELOG.md
  cli/cli.go
  cli/cli_test.go
  cli/importKeys_test.go
  internal/ui/prompterValidators.go
  internal/ui/prompterValidators_test.go
Labels: bug, go

#271 Update client images to shapella-ready version
  CHANGELOG.md
  configs/client_images.yaml
Labels: enhancement

#270 Update Nethermind client settings
  CHANGELOG.md
  configs/init.go
  templates/envs/chiado/execution/nethermind.tmpl
  templates/envs/custom/execution/nethermind.tmpl
  templates/envs/gnosis/execution/nethermind.tmpl
  templates/envs/goerli/execution/nethermind.tmpl
  templates/envs/mainnet/execution/nethermind.tmpl
  templates/envs/sepolia/execution/nethermind.tmpl
  templates/services/merge/execution/nethermind.tmpl
Labels: devops, go

#274 Fix: typos
  docs/docs/guidelines/new-clients.mdx
  docs/docs/hardware-requirements/index.md
  docs/docs/quickstart/complete-guide.mdx
  docs/docs/quickstart/install-guide.mdx
  docs/docs/troubleshoot.md
Labels: documentation
