Repository NethermindEth/sedge, pull requests merged in 2023-02, with the labels that each got.

#237 Update mev-boost relay URLs
  CHANGELOG.md
  templates/envs/goerli/env_base.tmpl
  templates/envs/mainnet/env_base.tmpl
Labels: enhancement

#238 Validator grace period bug
  .github/workflows/build.yml
  .github/workflows/check-version.yml
  .github/workflows/docs-deploy.yml
  .github/workflows/docs-test.yml
  .github/workflows/unit_tests.yml
  cli/actions/generation_test.go
  cli/generate.go
  cli/generate_test.go
  cli/run.go
  internal/pkg/generate/testdata/utils_tests/empty/docker-compose.yml
  internal/pkg/generate/testdata/utils_tests/invalid/docker-compose.yml
  internal/pkg/generate/testdata/utils_tests/no_compose/empty.txt
  internal/pkg/generate/testdata/utils_tests/valid/docker-compose.yml
  internal/pkg/generate/types.go
  internal/pkg/generate/utils.go
  internal/pkg/generate/utils_test.go
  internal/utils/testdata/validate_compose_tests/bad_env/.env
  internal/utils/testdata/validate_compose_tests/bad_services/docker-compose.yml
  internal/utils/testdata/validate_compose_tests/empty_env/.env
  internal/utils/testdata/validate_compose_tests/env_a/.env
  internal/utils/testdata/validate_compose_tests/env_b/.env
  internal/utils/testdata/validate_compose_tests/no_compose/empty.txt
  internal/utils/testdata/validate_compose_tests/no_env/docker-compose.yml
  internal/utils/testdata/validate_compose_tests/no_image/docker-compose.yml
  internal/utils/testdata/validate_compose_tests/no_services/.env
  internal/utils/testdata/validate_compose_tests/no_services/docker-compose.yml
  internal/utils/testdata/validate_compose_tests/no_version/.env
  internal/utils/testdata/validate_compose_tests/no_version/docker-compose.yml
  internal/utils/testdata/validate_compose_tests/valid/.env
  internal/utils/testdata/validate_compose_tests/valid/docker-compose.yml
  internal/utils/validate_compose.go
  internal/utils/validate_compose_test.go
Labels: bug, main, go

#240 Fix Prysm endpoint in check images updates script
  internal/pkg/generate/generate_scripts.go
  scripts/check-image-updates.sh
Labels: bug, devops

#241 Fix generate bugs
  cli/cli_utils.go
  cli/sub_gen.go
Labels: bug

#243 Add missing default ttd for gnosis and chiado network configs
  configs/init.go
Labels: bug

#246 Patch erigon image for TTD
  cli/cli.go
  cli/cli_utils.go
Labels: bug

#247 Consensus-Health utility service
  CHANGELOG.md
  cli/actions/generation_test.go
  cli/testdata/run_tests/no_env/docker-compose.yml
  cli/testdata/run_tests/no_image/docker-compose.yml
  cli/testdata/run_tests/no_services/.env
  cli/testdata/run_tests/no_version/.env
  cli/testdata/run_tests/no_version/docker-compose.yml
  cli/testdata/run_tests/valid/.env
  cli/testdata/run_tests/valid/docker-compose.yml
  internal/pkg/generate/generate_scripts.go
  internal/pkg/generate/generate_scripts_test.go
  internal/pkg/generate/types.go
  internal/utils/testdata/validate_compose_tests/no_env/docker-compose.yml
  internal/utils/testdata/validate_compose_tests/no_image/docker-compose.yml
  internal/utils/testdata/validate_compose_tests/no_services/.env
  internal/utils/testdata/validate_compose_tests/no_version/.env
  internal/utils/testdata/validate_compose_tests/no_version/docker-compose.yml
  internal/utils/testdata/validate_compose_tests/valid/.env
  internal/utils/testdata/validate_compose_tests/valid/docker-compose.yml
  templates/envs/chiado/env_base.tmpl
  templates/envs/custom/env_base.tmpl
  templates/envs/custom/validator/prysm.tmpl
  templates/envs/gnosis/env_base.tmpl
  templates/envs/goerli/env_base.tmpl
  templates/envs/goerli/validator/prysm.tmpl
  templates/envs/mainnet/env_base.tmpl
  templates/envs/mainnet/validator/prysm.tmpl
  templates/envs/sepolia/env_base.tmpl
  templates/envs/sepolia/validator/prysm.tmpl
  templates/services/consensus-health.tmpl
  templates/services/docker-compose_base.tmpl
  templates/services/empty-consensus-health.tmpl
  templates/services/merge/consensus/lighthouse.tmpl
  templates/services/merge/consensus/lodestar.tmpl
  templates/services/merge/consensus/prysm.tmpl
  templates/services/merge/consensus/teku.tmpl
  templates/services/merge/validator/lighthouse.tmpl
  templates/services/merge/validator/lodestar.tmpl
  templates/services/merge/validator/prysm.tmpl
  templates/services/merge/validator/teku.tmpl
Labels: bug, enhancement, go

#250 Fix error when sedge logs command is interrupted
  cli/actions/importKeys.go
  cli/actions/run.go
  cli/actions/run_test.go
  cli/actions/setup.go
  cli/actions/setup_test.go
  cli/cli_test.go
  cli/cli_utils.go
  cli/down.go
  cli/down_test.go
  cli/keys.go
  cli/logs.go
  cli/logs_test.go
  internal/pkg/commands/cmd_runner_helper_unix.go
  internal/pkg/commands/cmd_runner_unix.go
  internal/pkg/commands/cmd_runner_windows.go
  internal/pkg/commands/commands.go
  internal/pkg/commands/commands_unix_test.go
  internal/pkg/commands/commands_windows_test.go
  internal/utils/checks.go
  internal/utils/checks_test.go
  internal/utils/handle_dependencies_test.go
  test/test.go
Labels: bug, go
