Repository NethermindEth/sedge, pull requests merged in 2023-01, with the labels that each got.

#213 Windows add releases improvement
  .github/workflows/build.yml
  .github/workflows/check-version.yml
  .github/workflows/docs-test.yml
  .github/workflows/release.yml
  .github/workflows/unit_tests.yml
  Makefile
  internal/pkg/clients/clients_test.go
  internal/pkg/env/check_variable.go
  internal/pkg/generate/generate_scripts_test.go
  internal/utils/request.go
  scripts/build-go-darwin-binaries.sh
  scripts/build-go-linux-binaries.sh
  scripts/build-go-windows-binaries.ps1
Labels: devops

#159 Change data path from docker-compose-scripts to sedge-data
  .gitignore
  CHANGELOG.md
  cli/cli.go
  cli/cli_test.go
  cli/down.go
  cli/down_test.go
  cli/keys.go
  cli/logs.go
  cli/logs_test.go
  cli/run.go
  cli/slashingExport.go
  cli/testdata/down_tests/case_1/sedge-data/.env
  cli/testdata/down_tests/case_1/sedge-data/docker-compose.yml
  cli/testdata/logs_tests/case_1/sedge-data/.env
  cli/testdata/logs_tests/case_1/sedge-data/docker-compose.yml
  configs/messages.go
  docs/docs/quickstart/by-yourself.mdx
  internal/utils/checks.go
  internal/utils/checks_test.go
  internal/utils/testdata/checks_tests/case_1/sedge-data/.env
  internal/utils/testdata/checks_tests/case_1/sedge-data/docker-compose.yml
  internal/utils/testdata/checks_tests/case_2/sedge-data/.env
  internal/utils/testdata/checks_tests/case_2/sedge-data/no-docker-compose.yml
Labels: enhancement

#217 Update install scripts
  CHANGELOG.md
  configs/get_dependencies.go
  docs/docs/quickstart/dependencies.mdx
  go.mod
  go.sum
  internal/utils/handle_dependencies.go
  templates/setup/linux/docker/amzn_2.sh
  templates/setup/linux/docker/arch.sh
  templates/setup/linux/docker/arch_.sh
  templates/setup/linux/docker/debian_10.sh
  templates/setup/linux/docker/debian_11.sh
  templates/setup/linux/docker/debian_8.sh
  templates/setup/linux/docker/debian_9.sh
  templates/setup/linux/docker/ubuntu_20.04.sh
  templates/setup/linux/docker/ubuntu_22.04.sh
Labels: enhancement, dependencies

#173 Add documentation for supported networks and Clients
  CHANGELOG.md
  README.md
  docs/docs/networks/_category_.json
  docs/docs/networks/chiado.mdx
  docs/docs/networks/gnosis.mdx
  docs/docs/networks/goerli.mdx
  docs/docs/networks/mainnet.mdx
  docs/docs/networks/sepolia.mdx
Labels: documentation
