Repository NethermindEth/sedge, pull requests merged in 2023-03, with the labels that each got.

#257 URL validators unit tests
  cli/generate.go
  cli/generate_test.go
  configs/errors.go
  internal/utils/utils.go
  internal/utils/utils_test.go
Labels: enhancement, go

#256 Show only relay_url when mev-boost service is active
  cli/cli.go
  cli/sub_gen.go
  internal/pkg/generate/envs_test.go
  internal/pkg/generate/generate_scripts.go
  internal/pkg/generate/types.go
  internal/pkg/generate/types_test.go
  templates/envs/goerli/env_base.tmpl
  templates/envs/mainnet/env_base.tmpl
  templates/envs/sepolia/env_base.tmpl
Labels: bug, go

#258 Update docker api deprecated types
  cli/actions/importKeys_test.go
  cli/actions/slashing_test.go
  cli/cli.go
  internal/pkg/services/services.go
  internal/pkg/services/wait.go
  internal/pkg/services/wait_test.go
Labels: go

#259 Update lodestar validator data dir path
  cli/actions/slashing.go
  templates/services/merge/validator/lodestar.tmpl
Labels: bug

#261 Update documentation for release
  README.md
  cli/sub_gen.go
  docs/docs/commands/_category_.json
  docs/docs/commands/down.mdx
  docs/docs/commands/generate.mdx
  docs/docs/commands/keys.mdx
  docs/docs/commands/slashingExport.mdx
  docs/docs/commands/slashingImport.mdx
  docs/docs/concepts/_category_.json
  docs/docs/concepts/checkpoint-sync.md
  docs/docs/concepts/fee-recipient.md
  docs/docs/concepts/keystore.md
  docs/docs/hardware-requirements/_category_.json
  docs/docs/hardware-requirements/index.md
  docs/docs/hardware-requirements/mainnet.md
  docs/docs/hardware-requirements/testnets.md
  docs/docs/intro.md
  docs/docs/networks/chiado.mdx
  docs/docs/networks/gnosis.mdx
  docs/docs/networks/goerli.mdx
  docs/docs/networks/mainnet.mdx
  docs/docs/networks/sepolia.mdx
  docs/docs/quickstart/_category_.json
  docs/docs/quickstart/by-yourself.mdx
  docs/docs/quickstart/complete-guide.mdx
  docs/docs/quickstart/dependencies.mdx
  docs/docs/quickstart/index.md
  docs/docs/quickstart/install-guide.mdx
  docs/docs/quickstart/keys-management.mdx
  docs/docs/quickstart/restart-validator.mdx
  docs/docs/quickstart/run-validator.md
  docs/docs/quickstart/samples/_category_.json
  docs/docs/quickstart/samples/custom-bootnodes.mdx
  docs/docs/quickstart/samples/exposing-api.mdx
  docs/docs/quickstart/samples/migrate-current-setup.mdx
  docs/docs/quickstart/samples/run-validator-mev-goerli.md
  docs/docs/quickstart/samples/run-validator.md
  docs/docs/quickstart/samples/running-mev-boost.mdx
  docs/docs/quickstart/samples/setting-check-sync.mdx
  docs/docs/quickstart/samples/using-relays.mdx
  docs/docs/troubleshoot.md
Labels: documentation, main

#269 Put missing v on documentation wget and curl of binary
  docs/docs/quickstart/complete-guide.mdx
Labels: bug, documentation
